name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to EC2 Instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USERNAME }}
          key: ${{ secrets.AWS_EC2_KEY }}

          # Commands to execute on the EC2 instance
          script: |
            echo "Running- cd /media/honeycourses-frontend"
            cd /media/honeycourses-frontend
            echo "Running- sudo git pull"
            sudo git pull
            echo "Running- sudo yarn install"
            sudo yarn install --ignore-engines
            echo "Running- sudo yarn build"
            sudo yarn build
            echo "Running- sudo chmod -R +x /var/www/html"
            sudo chmod -R +x /var/www/html
            echo "Running- sudo rm -r /var/www/html/*"
            sudo rm -r /var/www/html/*
            echo "Running- sudo cp -r build/* /var/www/html"
            sudo cp -r build/* /var/www/html
            echo "Running- cd /var/www/html"
            cd /var/www/html
            echo "Running- sudo chmod -R +x /var/www/html"
            sudo chmod -R +x /var/www/html
            echo "Running- sudo mv build/* ."
            sudo mv build/* .
            echo "Running- sudo systemctl restart nginx"
            sudo systemctl restart nginx
            sudo systemctl status nginx
